name: robotlabExperiments
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy<2.0
  - scikit-learn
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - toml
  - pip
  - pip:
    - pyyaml
    - ../ActiveLearningCLassiFier/
    - -e ./
