experimentID: 'experiment_name'
cycleN: 0
rngSeed:  # if empty -> None -> random seed else needs int

dataset: 'path/to/your/validation_data.csv'
targetVariable: 'Phase'

validatedset:

newBatch: 18

clfModel: 
kParam1: 
kParam2: 
clf_dict:
  # if empty -> None, else needs kwargs from classifier definition

acqMode: 
entropyDecimals: 

screeningSelection: 
