experimentID: 'experiment_name'
cycleN: X # number of the cycle, x > 0
rngSeed:  # if empty -> None -> random seed else needs int

dataset: 'path/to/your/validation_data.csv'
targetVariable: 'Phase'

validatedset: 'path/to/prev_cycle/validated_data.csv'

newBatch: 18

clfModel: 'GaussianProcessClassifier'
kParam1: 1.0  # constant parameter
kParam2: 1.0  # lenght scale
clf_dict:
  n_restarts_optimizer: 5
  max_iter_predict: 200
  # if empty -> None, else needs kwargs from classifier definition

acqMode: 'exploration'
entropyDecimals: 2

screeningSelection: 'FPS'
